baseURL = 'https://example.org/'
languageCode = 'en-gb'
defaultContentLanguage = 'en-gb'
title = 'Litong Wu'
pagination.paperSize = 10

# hugo-coder config, see
# https://github.com/luizdepra/hugo-coder/blob/main/docs/configurations.md
[params]
author = 'Litong Wu'
altAuthor = '<span lang="zh-cn">吴莉彤</span>'
description = 'Litong Wu’s homepage'
katex = true
dateFormat = '2 Jan 2006'
customSCSS = ['scss/custom.scss']
hideColorSchemeToggle = true

# use CSS for syntax highlighting
[markup.highlight]
noClasses = false

[markup.tableOfContents]
startLevel = 2
endLevel = 2

[markup.goldmark.renderer]
unsafe = true

[languages.en-gb]
languageName = 'en' # Display name

[[languages.en-gb.menu.main]]
name = 'Home'
weight = 1
url = '/'

[[languages.en-gb.menu.main]]
name = 'Research'
weight = 2
url = '/research/'

# [[languages.en-gb.menu.main]]
# name = '`Blog`'
# weight = 3
# url = '/posts/'

[[languages.en-gb.menu.main]]
name = 'About'
weight = 4
url = '/about/'